#define CWH_DISPLAY (uiNamespace getVariable[QGVAR(rscHUD), displayNull])

#define CWH_CTRL_SUNFILTER (CWH_DISPLAY displayCtrl 1001)
#define CWH_CTRL_FRAME (CWH_DISPLAY displayCtrl 1002)
#define CWH_CTRL_COLOR (CWH_DISPLAY displayCtrl 1003)

#define CWH_CTRL_WEAPON_FRAME (CWH_DISPLAY displayCtrl 1010)
#define CWH_CTRL_WEAPON_ICON (CWH_DISPLAY displayCtrl 1011)
#define CWH_CTRL_WEAPON_BULLET_COUNT (CWH_DISPLAY displayCtrl 1012)
#define CWH_CTRL_WEAPON_INFO (CWH_DISPLAY displayCtrl 1013)
#define CWH_CTRL_WEAPON_MAGAZINE_ICON (CWH_DISPLAY displayCtrl 1014)
#define CWH_CTRL_WEAPON_MAGAZINE_COUNT (CWH_DISPLAY displayCtrl 1015)
#define CWH_CTRL_WEAPON_FIREMODE_5 (CWH_DISPLAY displayCtrl 10165)
#define CWH_CTRL_WEAPON_FIREMODE_4 (CWH_DISPLAY displayCtrl 10164)
#define CWH_CTRL_WEAPON_FIREMODE_3 (CWH_DISPLAY displayCtrl 10163)
#define CWH_CTRL_WEAPON_FIREMODE_2 (CWH_DISPLAY displayCtrl 10162)
#define CWH_CTRL_WEAPON_FIREMODE_1 (CWH_DISPLAY displayCtrl 10161)

#define CWH_CTRL_GRENADE_FRAME (CWH_DISPLAY displayCtrl 1020)
#define CWH_CTRL_GRENADE_ICON (CWH_DISPLAY displayCtrl 1021)
#define CWH_CTRL_GRENADE_COUNT (CWH_DISPLAY displayCtrl 1022)

#define CWH_CTRL_DIR_FRAME (CWH_DISPLAY displayCtrl 1030)
#define CWH_CTRL_DIR_INFO (CWH_DISPLAY displayCtrl 1031)

#define CWH_CTRL_CRACK (CWH_DISPLAY displayCtrl 1100)

// List of all HUD controls
#define CWH_CTRL_WEAPON [ CWH_CTRL_WEAPON_FRAME, CWH_CTRL_WEAPON_ICON, CWH_CTRL_WEAPON_BULLET_COUNT, CWH_CTRL_WEAPON_INFO, CWH_CTRL_WEAPON_MAGAZINE_ICON, CWH_CTRL_WEAPON_MAGAZINE_COUNT, CWH_CTRL_WEAPON_FIREMODE_5, CWH_CTRL_WEAPON_FIREMODE_4, CWH_CTRL_WEAPON_FIREMODE_3, CWH_CTRL_WEAPON_FIREMODE_2, CWH_CTRL_WEAPON_FIREMODE_1 ]
#define CWH_CTRL_GRENADE [ CWH_CTRL_GRENADE_FRAME, CWH_CTRL_GRENADE_ICON, CWH_CTRL_GRENADE_COUNT ]
#define CWH_CTRL_DIR [ CWH_CTRL_DIR_FRAME, CWH_CTRL_DIR_INFO ]
#define CWH_CTRL_ALL [ CWH_CTRL_FRAME, CWH_CTRL_COLOR ] + CWH_CTRL_WEAPON + CWH_CTRL_GRENADE + CWH_CTRL_DIR

#define CWH_CTRL_COLORED [ CWH_CTRL_COLOR, CWH_CTRL_WEAPON_FRAME, CWH_CTRL_GRENADE_FRAME, CWH_CTRL_DIR_FRAME ]

// Color
#define CWH_COLOR_DEFAULT 0,0.447,0.741,1 // Default blue
#define CWH_COLOR_DISABLED 0.5,0.5,0.5,1 // Grey
#define CWH_COLOR_WHITE 1,1,1,1 // White
