#define CWH_DISPLAY (uiNamespace getVariable [QGVAR(rscHUD), displayNull])

#define CWH_CTRL_WEAPON_FRAME (CWH_DISPLAY displayCtrl 1010)
#define CWH_CTRL_WEAPON_ICON (CWH_DISPLAY displayCtrl 1011)
#define CWH_CTRL_WEAPON_BULLET_COUNT (CWH_DISPLAY displayCtrl 1012)
#define CWH_CTRL_WEAPON_INFO (CWH_DISPLAY displayCtrl 1013)
#define CWH_CTRL_WEAPON_MAGAZINE_ICON (CWH_DISPLAY displayCtrl 1014)
#define CWH_CTRL_WEAPON_MAGAZINE_COUNT (CWH_DISPLAY displayCtrl 1015)

#define CWH_CTRL_GRENADE_FRAME (CWH_DISPLAY displayCtrl 1020)
#define CWH_CTRL_GRENADE_ICON (CWH_DISPLAY displayCtrl 1021)
#define CWH_CTRL_GRENADE_COUNT (CWH_DISPLAY displayCtrl 1022)

#define CWH_CTRL_DIR_FRAME (CWH_DISPLAY displayCtrl 1030)
#define CWH_CTRL_DIR_ICON (CWH_DISPLAY displayCtrl 1031)
